### ISSUE TITLE
GitHub Actions workflows for desktop/web binaries

### ISSUE THREAD

**Issue by anirudhb** [enbox/enbox#5]
Tracking issue for adding workflows to build desktop/web binaries to GitHub Actions.
This should ideally build all branches (except gh-pages) and PRs as well.

Checklist:
- [x] Windows support
- [x] Mac support
- [x] Linux support
- [x] Web support (see [here](https://github.com/enbox/enbox/blob/master/.github/workflows/deploy_web_to_gh_pages.yml#L14) as a guide)

**Comment by Treeways** [comment]
There's still bugs with the CI workflows.
